### ISSUE TITLE
Investigate using `reservedWordsMapping` to control acronym casing

### ISSUE THREAD

**Issue by ctreatma** [equinix-labs/metal-go#112]
This SDK was recently updated to use openapi-generator v6.6.0.  That version adds support for `reservedWordsMapping` in the Go generator: https://github.com/OpenAPITools/openapi-generator/pull/15083

We may be able to use `reservedWordsMapping` to standardize how certain acronyms (`Bgp`/`BGP`, `Vrf`/`VRF`, etc.) are capitalized in generated code.

Try adding a reserved words mapping to this SDK to see if that feature will enable us to standardize acronym capitalization without introducing unintended side effects.

**Comment by displague** [comment]
`Id=ID` seems to not be too aggressive for this project. It may be unnecessary based on upstream changes to follow Go initialisms recommendations. Nonetheless, the diff still included `ById` methods.

**Comment by ctreatma** [comment]
Closing; while the acronym casing might not match our ideal, it nonetheless works.  In our limited experimentation with openapi-generator options, none of them really provided the ideal output.  If the Metal team wants to put more effort into changing acronym casing, they should do that in [equinix/equinix-sdk-go](https://github.com/equinix/equinix-sdk-go).
