### ISSUE TITLE
Missing properties to VirtualNetwork

### ISSUE THREAD

**Issue by codinja1188** [equinix-labs/metal-go#117]
Observed  Missing properties to VirtualNetwork.

```
VirtualNetwork.FacilityCode()
VirtualNetwork.CreatedAt.string()
```

https://github.com/packethost/packngo/blob/master/virtualnetworks.go#L17-L29

**Comment by ctreatma** [comment]
`VirtualNetwork.CreatedAt` was added in #121, released in `v0.16.0`.  `VirtualNetwork.FacilityCode()` is still absent, but given that facilities are deprecated, we could take this opportunity to stop showing facility to customers.  If we absolutely need to show facility code, we could also get at that attribute by asking the API to include facility attributes with `.Include([]string{"facility"})` and then accessing the `code` attributes at `virtual_network.facility.AdditionalProperties["code"]` (`VirtualNetwork.Facility` is currently defined as an `Href` in the spec, so the only named property it has is `href`, but we can use `AdditionalProperties` to get at unnamed properties).
