### ISSUE TITLE
Invitations Create API misplaced at Organizations API service

### ISSUE THREAD

**Issue by codinja1188** [equinix-labs/metal-go#118]
As per packngo, the InvitationApiService has a create() method, but it is available at the Organizations API service in Metal-go. 

Is this move happened knowingly OR was it misplaced?

@displague @ctreatma 

Plz correct me if I am wrong

**Comment by displague** [comment]
packngo service definitions are chosen by the packngo developer. In metal-go, the definitions are drawn from the OAS3 tags, which serve multiple purposes, including determining where the endpoint lives in documentation.

If invitations have /organization in the URL, Organization placement seems reasonable.

**Comment by vasubabu** [comment]
okay, looks like missing --includes and --excludes to the API.

**Comment by ctreatma** [comment]
It seems like we came to the conclusion that it is reasonable for this endpoint to be where it is in the SDK, and I see that the API spec has been updated to document the parameters this endpoint accepts.  Closing this issue.  If there are still problems with the invitations endpoint, an issue should be created in [equinix/equinix-sdk-go](https://github.com/equinix/equinix-sdk-go).
