### ISSUE TITLE
Remove the experimental label

### ISSUE THREAD

**Issue by displague** [equinix-labs/metal-go#175]
The experimental label is preventing adoption of this SDK. This has been by design as we've been building this project from the ground up using code generation, learning the limitations and fixing the upstream API spec to accommodate code generation needs along the way.

With #99, and meeting the expectations of that issue, we'll want to remove the experimental labels and warnings from this project.

Ahead of deprecating packngo we want to see that metal-go is suitable for several of our public integrations (Metal CLI, cluster-api, cloud-provider-equinix-metal, Terraform). When this work is done, metal-go will have proven that it is more important and vetted than 'experimental'. It will be necessary to maintain it for continued development in the aforementioned integrations.

**Comment by ctreatma** [comment]
This has been addressed in [equinix/equinix-sdk-go](https://github.com/equinix/equinix-sdk-go) and will not be implemented here.
