### ISSUE TITLE
Consider moving the code generation to a seperate project

### ISSUE THREAD

**Issue by displague** [equinix-labs/metal-go#41]
Consider moving the code generation to a separate project so that this tooling can be used with alternative but related versions of the spec.

One benefit of moving the tooling out of the root is that the client may be more accessible. We currently have some oddities with how go.mod/go.sum is generated and consumed.  Perhaps we can learn more from #40 .

Those projects would benefit from common tooling and may benefit from shared patchsets.

On the other hand, the patchsets may be difficult to share with alternate versions of the API.  With OpenAPIv3 we would have the ability to merge multiple files together. Adopting OpenAPIv3 upstream may give us this benefit earlier.

**Comment by ctreatma** [comment]
I don't think this issue is relevant any more; if there's something in this issue that we still need to do, it can be added as an issue on [equinix/equinix-sdk-go](https://github.com/equinix/equinix-sdk-go).
