### ISSUE TITLE
Demonstrate pagination

### ISSUE THREAD

**Issue by displague** [equinix-labs/metal-go#6]
Methods like `FindProjectDevices` accept a `FindProjectDevicesParams` parameter which includes the `Page` and `Include` parameters that `packngo` offers. What does it look like to use these parameters in this client? (provide a new example/ for this). How do we access the total page count when we are making a single page request?

Is it possible to have the client pre-fetch all paginated results, as we do in `packngo`?

https://github.com/packethost/packngo/blob/4d8131c50dd3045729772fa5a92f88b1d93556a0/devices.go#L342-L363

What does that look like with a go-swagger generated client?
This may require #3.

Can we include the `Sort` parameter in these requests? 
Can we include the `Search` parameter in these requests? 

Is the swagger spec reporting these metadata fields correctly? (We can patch in support, can we do this broadly so that one common type is generated instead of duplicating these fields in each Params definition?)

**Comment by displague** [comment]
Basic pagination was demonstrated in #23.

I'd like to find a way to introduce a pagination helper or add generated autoscrolling List methods whenever we generate a `Find` method.  https://github.com/jsilland/go-swagger-cli is an example of how we can add generators using go-swagger.

I tried to use that project to generate a cli for `gometal`, but some of the types were not handled: https://github.com/t0mk/gometal/compare/main...displague:cli?expand=1

Another approach would be to use a custom RoundTripper to paginate. This is apparently not a good idea according to the RoundTripper docs (don't look at the response):
* https://lanre.wtf/blog/2017/07/24/roundtripper-go/
* https://pkg.go.dev/net/http#RoundTripper

**Comment by displague** [comment]
`Include` is included in the parameters of the `FindFoo` client methods. This parameter can be modified with `SetInclude`.
`Search` is also made available this way.

`SortBy` and `Exclude` are not included in the API docs.  I have made a contribution to these docs to introduce `Exclude`. I will make another for `SortBy` (and `SortDirection`).

**Comment by ctreatma** [comment]
Auto-pagination methods were added in #150 and we have examples of their usage in a few places.
