### ISSUE TITLE
Demonstrate Filtering

### ISSUE THREAD

**Issue by displague** [equinix-labs/metal-go#7]
Methods like `FindProjectDevices` accept a `FindProjectDevicesParams` parameter which includes the `Page` and `Include` parameters that `packngo` offers. What does it look like to use these parameters in this client? (provide a new example/ for this).

Is it possible to have the client set `Includes` and `Excludes` for any List method? Can this be done generically, as we do in `packngo`? What does this look like?

This may require #3.

**Comment by ctreatma** [comment]
We have a number of examples of using these parameters in `metal-cli`, `terraform-provider-equinix`, and at least one in this repo; those examples will continue to apply to `equinix-sdk-go` and the ones from this repo have been copied in that repo.
