### ISSUE TITLE
Deprecate Packngo

### ISSUE THREAD

**Issue by displague** [equinix-labs/metal-go#99]
Drive Metal Go to the level where we can safely deprecate packngo and promote metal-go.

Related:
- packethost/packngo#213
- packethost/packngo#215

Integrations that have converted from packngo to metal-go are the best way to help developers adapt their projects. Implementation examples include:
* [x] https://github.com/equinix/metal-cli/pull/333
* [x] https://github.com/equinix/terraform-provider-equinix/pull/291
* [x] https://github.com/equinix/terraform-provider-equinix/issues/402
* [x] https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/527
* [x] https://github.com/kubernetes-sigs/cloud-provider-equinix-metal/issues/439
* [x] https://github.com/equinix-labs/metal-sweeper-action/issues/12
* [x] https://github.com/equinix/docker-machine-driver-metal/issues/77

Should be done with #175.

**Comment by ctreatma** [comment]
This repo has been replaced by [equinix/equinix-sdk-go](https://github.com/equinix/equinix-sdk-go).  The remaining work to transition terraform-provider-equinix from packngo to equinix-sdk-go is being tracked in that repository.  The packngo SDK has been deprecated and the repo is archived.
